### ISSUE TITLE
Visualizar as inscrições por área de atuação/segmento

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/EvaluationMethodDocumentarySefic#8]
Eu como gerente do edital quero visualizar as inscrições dos candidatos com o número de inscrição da primeira fase.

Condições de aceitação:
- [x] A lista de inscritos a partir da segunda fase apresentam o segmento e número de inscrição da primeira fase

**Comment by avaloni** [comment]
Alterar as seguintes telas:

- Tabela de inscritos
- Tabela de avaliações
- Single de exibição da inscrição
