### ISSUE TITLE
Avaliador altera o status da inscrição ao finalizar a avaliação

### ISSUE THREAD

**Issue by marcus2703** [culturagovbr/EvaluationMethodDocumentarySefic#9]
Eu como avaliador após finalizar a avaliação de uma inscrição quero alterar o status da avaliação na lista de inscritos.

Condições de aceitação:
- [ ] Na visualização da listagem de inscritos o campo Avaliação e Todos devem ter o mesmo resultado.

**Comment by Pedro-Philipe** [comment]
- [ ] Durante a avaliação documental é necessário escolher a avaliação 

- [ ] O campo de parecer deve ser obrigatório
